#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr &

picom &
nitrogen --restore &
start-pulseaudio-x11 &
polybar main -c ~/.config/polybar/config.ini &

bspc monitor -d I

bspc config window_gap		       12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#282828"
bspc config focused_border_color "#928374"

bspc rule -a mpv state=floating
bspc rule -a discord state=floating
bspc rule -a Pcmanfm state=floating
